<a href="https://colab.research.google.com/github/mirpouya/Introduction-to-PyTorch/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**<h2> Tensors </h2>**

In [2]:
# making an empty tensor

x = torch.empty(3)
x

# values are not initialized

tensor([0., 0., 0.])

In [3]:
x = torch.empty(2,3)

In [4]:
x

tensor([[0.0000e+00, 6.2121e+22, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 2.6222e-09]])

In [6]:
# tensors with random values

x = torch.rand(2,4)
x

tensor([[0.4668, 0.5965, 0.4280, 0.7782],
        [0.3246, 0.2997, 0.2306, 0.0424]])

In [7]:
x = torch.ones(2,3,4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# shape of a tensor

x.size()

torch.Size([2, 3, 4])

In [11]:
x1 = torch.rand(2,3)
print(f"x1 : {x1}")

x2 = torch.ones(2,3)
print(f"x2 : {x2}")

# adding x2 to x1

x1.add_(x2)
print(f"x1 : {x1}")

x1 : tensor([[0.1599, 0.0188, 0.7589],
        [0.8851, 0.7231, 0.3647]])
x2 : tensor([[1., 1., 1.],
        [1., 1., 1.]])
x1 : tensor([[1.1599, 1.0188, 1.7589],
        [1.8851, 1.7231, 1.3647]])


In [12]:
# in pyorch every function that has underline "_" at the end, does an inplace opperation
# these three are the same

x = torch.ones(3)
y = torch.rand(3)
z = torch.sub(x,y)


print(f"x - y : {x - y}\n")
print(f"z : {z}\n")

x.sub_(y)
print(f"x.sub_(y) : {x}\n")

x - y : tensor([0.7956, 0.8260, 0.2597])

z : tensor([0.7956, 0.8260, 0.2597])

x.sub_(y) : tensor([0.7956, 0.8260, 0.2597])



In [13]:
# reshaping tensor

x = torch.rand(3,4)

print(f"x is : {x}\n")
print(f"shape of x is : {x.size()}\n")

x2 = x.view(2,6)

print(f"x2 is : {x2}\n")
print(f"shape of x2 is : {x2.size()}\n")

x is : tensor([[0.7925, 0.0155, 0.2878, 0.1505],
        [0.3759, 0.0037, 0.9361, 0.5885],
        [0.9568, 0.3740, 0.2912, 0.0719]])

shape of x is : torch.Size([3, 4])

x2 is : tensor([[0.7925, 0.0155, 0.2878, 0.1505, 0.3759, 0.0037],
        [0.9361, 0.5885, 0.9568, 0.3740, 0.2912, 0.0719]])

shape of x2 is : torch.Size([2, 6])



In [14]:
# consider we want to reshape a tensor, and we want to pass one of the new dimensions
# so pytorch calculate other dimensions with respect to what we passed

x = torch.rand(4,6)
print(f"x is : {x}\n")
print(f"shape of x is : {x.size()}\n")

x2 = x.view(-1,2,4)
print(f"x is : {x2}\n")
print(f"shape of x2 is : {x2.size()}\n")

x is : tensor([[0.0606, 0.1286, 0.4998, 0.2304, 0.3392, 0.5274],
        [0.5542, 0.5074, 0.9697, 0.3876, 0.7143, 0.4914],
        [0.7388, 0.5923, 0.6806, 0.5152, 0.9428, 0.3457],
        [0.0578, 0.1214, 0.8202, 0.2884, 0.5604, 0.0423]])

shape of x is : torch.Size([4, 6])

x is : tensor([[[0.0606, 0.1286, 0.4998, 0.2304],
         [0.3392, 0.5274, 0.5542, 0.5074]],

        [[0.9697, 0.3876, 0.7143, 0.4914],
         [0.7388, 0.5923, 0.6806, 0.5152]],

        [[0.9428, 0.3457, 0.0578, 0.1214],
         [0.8202, 0.2884, 0.5604, 0.0423]]])

shape of x2 is : torch.Size([3, 2, 4])



In [15]:
# numpy

import numpy as np

In [19]:
# sometimes you need to change numpy arrays to tensors

np_arr = np.random.randn(2,4)
print(f" np_arr : {np_arr}\n type: {type(np_arr)}\n")

tensor_arr = torch.from_numpy(np_arr)
print(f" tensor_arr : {tensor_arr}\n type: {type(tensor_arr)}")

 np_arr : [[-0.89827763  1.01065498 -0.07502199 -2.44255049]
 [-0.39961354  0.61091852  0.1645482   0.16746311]]
 type: <class 'numpy.ndarray'>

 tensor_arr : tensor([[-0.8983,  1.0107, -0.0750, -2.4426],
        [-0.3996,  0.6109,  0.1645,  0.1675]], dtype=torch.float64)
 type: <class 'torch.Tensor'>


In [21]:
# most of the time we train our model on GPU 
# to check if the option of training the model is available we can

if torch.cuda.is_available():
  # specify cuda device
  device = torch.device("cuda")

  # for creating a tensor on the GPU
  x = torch.ones((2,4), device=device)

  # or first create it and then move it to device
  y = torch.ones(2,4)
  y = y.to(device)

  # if any operation needs x and y it will be fulfilled on the device (GPU)
  z = x+y

  # remember, numpy can only handle CPU tensors 