<a href="https://colab.research.google.com/github/mirpouya/Introduction-to-PyTorch/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

**<h2> Tensors </h2>**

In [2]:
# making an empty tensor

x = torch.empty(3)
x

# values are not initialized

tensor([0., 0., 0.])

In [3]:
x = torch.empty(2,3)

In [4]:
x

tensor([[0.0000e+00, 6.2121e+22, 1.8788e+31],
        [1.7220e+22, 2.1715e-18, 2.6222e-09]])

In [6]:
# tensors with random values

x = torch.rand(2,4)
x

tensor([[0.4668, 0.5965, 0.4280, 0.7782],
        [0.3246, 0.2997, 0.2306, 0.0424]])

In [7]:
x = torch.ones(2,3,4)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# shape of a tensor

x.size()

torch.Size([2, 3, 4])

In [11]:
x1 = torch.rand(2,3)
print(f"x1 : {x1}")

x2 = torch.ones(2,3)
print(f"x2 : {x2}")

# adding x2 to x1

x1.add_(x2)
print(f"x1 : {x1}")

x1 : tensor([[0.1599, 0.0188, 0.7589],
        [0.8851, 0.7231, 0.3647]])
x2 : tensor([[1., 1., 1.],
        [1., 1., 1.]])
x1 : tensor([[1.1599, 1.0188, 1.7589],
        [1.8851, 1.7231, 1.3647]])


In [12]:
# in pyorch every function that has underline "_" at the end, does an inplace opperation
# these three are the same

x = torch.ones(3)
y = torch.rand(3)
z = torch.sub(x,y)


print(f"x - y : {x - y}\n")
print(f"z : {z}\n")

x.sub_(y)
print(f"x.sub_(y) : {x}\n")

x - y : tensor([0.7956, 0.8260, 0.2597])

z : tensor([0.7956, 0.8260, 0.2597])

x.sub_(y) : tensor([0.7956, 0.8260, 0.2597])

